palette = "customColors"

format = """
[](color1)\
$username\
$hostname\
[](bg:color2 fg:color1)\
$directory\
[](fg:color2 bg:color3)\
$aws\
$git_branch\
[ ](fg:color3)\
"""

# Uncomment for demos
# format = """
# [](color1)\
# $username\
# [ ](color1)\
# """

add_newline = false

[username]
show_always = true
style_user = "bg:color1 text1"
style_root = "bg:color1 text1"
format = '[λ ]($style)'
disabled = false

[hostname]
ssh_only = false
style = "bg:color1 text1"
format = '[$hostname ]($style)'
aliases =  {
    "Oscars-MacBook-Pro"= "work"
}
disabled = false


[directory]
style = "bg:color2 text2"
format = "[ $path ]($style)"
truncation_length = 3

[directory.substitutions]
# "Documents" = "󰈙 "

[git_branch]
symbol = ""
style = "bg:color3 text2"
format = '[ $symbol $branch ]($style)'

[palettes.customColors]
color1 = '#d60270'
color2 = '#9b4f96'
color3 = '#0038a8'
text1 = '#e8e8e8'
text2 = '#e8e8e8'

[aws]
format = '[ $symbol ($profile) -]($style)'
symbol = ''
style = 'bg:color3 text2'
disabled = false
