palette = "customColors"

format = """
[](color1)\
$username\
[](bg:color2 fg:color1)\
$directory\
[](fg:color2 bg:color3)\
$git_branch\
[ ](fg:color3)\
"""

add_newline = false

[username]
show_always = true
style_user = "bg:color1 text1"
style_root = "bg:color1 text1"
format = '[λ ]($style)'
disabled = false

[directory]
style = "bg:color2 text2"
format = "[ $path ]($style)"
truncation_length = 3

[directory.substitutions]
# "Documents" = "󰈙 "

[git_branch]
symbol = ""
style = "bg:color3 text2"
format = '[ $symbol $branch ]($style)'

[palettes.customColors]
color1 = '#d20f39'
color2 = '#ca9ee6'
color3 = '#6084ce'
text1 = '#c0c4c1'
text2 = '#181616'
